# Generated by Django 3.2.9 on 2021-12-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0002_auto_20211203_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrow',
            field=models.BooleanField(default=False),
        ),
    ]
